Using pretrained: False
number of unique_entities -> 1685
number of unique_entities -> 1539
number of unique_entities -> 1598
Training size 2 Val size 2 Test size 2
Initialised relations and entities randomly
Graph created
length of graph keys is  1685
time taken  74.9655442237854
length of neighbors dict is  1685
Total triples count 192259, training triples 134598, validation_triples 19228, test_triples 38433
Opening node_neighbors pickle object
Initial entity dimensions torch.Size([1710, 50]) , relation dimensions torch.Size([86, 50])
Defining model
Only Conv model trained
Traceback (most recent call last):
  File "main.py", line 432, in <module>
    train_conv(args)
  File "main.py", line 334, in train_conv
    model_conv.load_state_dict(torch.load(args.load_conv))
  File "/scratch/bz1030/anaconda3/envs/capstone/lib/python3.7/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/bz1030/relationPrediction/checkpoints/deepddi_tanh/conv/trained_11.pth'
